### ISSUE TITLE
IR Compiler Error After Upgrade to 5.3.0

### ISSUE THREAD

**Issue by gad2103** [robertfmurdock/jsmints#600]
Hey Rob, our create by pull request job is failing after trying to update to the 5.3.0 version of the library. Specifically we are seeing an error when the `compileProductionExecutableKotlinJs` gradle task that looks like it comes from the ReactFunction file. Please see the stacktrace below. Any help would be much appreciated.

```
file:///home/runner/work/jsmints/jsmints/libraries/minreact/src/jsMain/kotlin/com/zegreatrob/minreact/ReactFunction.kt:37:1 org.jetbrains.kotlin.backend.common.CompilationException: Back-end: Please report this problem https://kotl.in/issue
/home/runner/work/jsmints/jsmints/libraries/minreact/src/jsMain/kotlin/com/zegreatrob/minreact/ReactFunction.kt:37:1
Problem with `class NamedFC<T : Props> {
  constructor(function: @/* ERROR: unexpected parent for <init> */() @ExtensionFunctionType Function2<ChildrenBuilder, T, Unit>) /* primary */ {
    super/*Any*/()
    /* <init>() */

  }

  private fun <get-function>(): @/* ERROR: unexpected parent for <init> */() @ExtensionFunctionType Function2<ChildrenBuilder, T, Unit> {
    return <this>.#function
  }

  private /* final field */ val function: @/* ERROR: unexpected parent for <init> */() @ExtensionFunctionType Function2<ChildrenBuilder, T, Unit> = function
  private fun <set-fc>(<set-?>: FC<T>?) {
    <this>.#fc = <set-?>
  }

  private fun <get-fc>(): FC<T>? {
    return <this>.#fc
  }

  private var fc: FC<T>? = null
  operator fun <A : Any?> getValue(t: A?, property: KProperty<*>): FC<T> {
    return { // BLOCK
      val tmp0_elvis_lhs: FC<T>? = <this>.<get-fc>()
      when {
        EQEQ(arg0 = tmp0_elvis_lhs, arg1 = null) -> { // RETURNABLE BLOCK
          { // INLINED FUNCTION BLOCK
            // COMPOSITE {
            val this: Any? = { // BLOCK
              FC<T>(displayName = property.<get-name>(), block = <this>.<get-function>())
            }
            // }
            { // RETURNABLE BLOCK
              { // INLINED FUNCTION BLOCK
              }
            }
            { // RETURNABLE BLOCK
              { // INLINED FUNCTION BLOCK
                // COMPOSITE {
                val it: FC<T> = { // BLOCK
                  this
                }
                // }
                <this>.<set-fc>(<set-?> = it)
              }
            }
            return this
          }
        }
        true -> tmp0_elvis_lhs
      }
    }
  }

  /* fake */ override operator fun equals(other: Any?): Boolean

  /* fake */ override fun hashCode(): Int

  /* fake */ override fun toString(): String

}

`
Details: Internal error in body lowering: java.lang.IllegalStateException: Parent of this declaration is not a class: CONSTRUCTOR MISSING_DECLARATION visibility:public <> () returnType:kotlin.Nothing
	at org.jetbrains.kotlin.ir.util.IrUtilsKt.getParentAsClass(IrUtils.kt:328)
	at org.jetbrains.kotlin.backend.common.serialization.IrBodyDeserializer$IrAnnotationType.resolveType(IrBodyDeserializer.kt:206)
	at org.jetbrains.kotlin.backend.common.serialization.IrBodyDeserializer$IrAnnotationType.access$resolveType(IrBodyDeserializer.kt:196)
	at org.jetbrains.kotlin.backend.common.serialization.IrBodyDeserializer$IrAnnotationType$delegate$2.invoke(IrBodyDeserializer.kt:200)
	at org.jetbrains.kotlin.backend.common.serialization.IrBodyDeserializer$IrAnnotationType$delegate$2.invoke(IrBodyDeserializer.kt:200)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at org.jetbrains.kotlin.backend.common.serialization.IrBodyDeserializer$IrAnnotationType.getDelegate(IrBodyDeserializer.kt:200)
	at org.jetbrains.kotlin.ir.types.impl.IrDelegatedSimpleType.getClassifier(IrSimpleTypeImpl.kt:45)
	at org.jetbrains.kotlin.ir.util.DeepCopyTypeRemapper.remapType(DeepCopyTypeRemapper.kt:34)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.remapType(DeepCopyIrTreeWithSymbols.kt:86)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitConstructorCall(DeepCopyIrTreeWithSymbols.kt:567)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitConstructorCall(DeepCopyIrTreeWithSymbols.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:218)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitConstructorCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrConstructorCall.accept(IrConstructorCall.kt:28)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.util.DeepCopyTypeRemapper.remapType(DeepCopyTypeRemapper.kt:37)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.remapType(DeepCopyIrTreeWithSymbols.kt:86)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitGetValue(DeepCopyIrTreeWithSymbols.kt:522)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitGetValue(DeepCopyIrTreeWithSymbols.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:194)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitGetValue(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrGetValue.accept(IrGetValue.kt:20)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitSetField(DeepCopyIrTreeWithSymbols.kt:1030)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitSetField(DeepCopyIrTreeWithSymbols.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSetField(IrElementTransformerVoid.kt:206)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitSetField(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrSetField.accept(IrSetField.kt:23)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitBlock(DeepCopyIrTreeWithSymbols.kt:1015)
	at org.jetbrains.kotlin.ir.util.DeepCopyIrTreeWithSymbols.visitBlock(DeepCopyIrTreeWithSymbols.kt:53)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:170)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitBlock(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrBlock.accept(IrBlock.kt:20)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.backend.common.lower.InitializersLowering$lower$2.visitInstanceInitializerCall(InitializersLowering.kt:134)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitInstanceInitializerCall(IrElementTransformerVoid.kt:258)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoid.visitInstanceInitializerCall(IrElementTransformerVoid.kt:24)
	at org.jetbrains.kotlin.ir.expressions.IrInstanceInitializerCall.accept(IrInstanceInitializerCall.kt:23)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:31)
	at org.jetbrains.kotlin.ir.expressions.IrExpression.transform(IrExpression.kt:22)
	at org.jetbrains.kotlin.ir.util.TransformKt.transformInPlace(transform.kt:35)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.transformChildren(IrBlockBody.kt:32)
	at org.jetbrains.kotlin.ir.visitors.IrElementTransformerVoidKt.transformChildrenVoid(IrElementTransformerVoid.kt:346)
	at org.jetbrains.kotlin.backend.common.lower.InitializersLowering.lower(InitializersLowering.kt:49)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor$visitBody$1.invoke(Lower.kt:193)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor$visitBody$1.invoke(Lower.kt:192)
	at org.jetbrains.kotlin.ir.backend.js.WholeWorldStageController.restrictTo(WholeWorldStageController.kt:29)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:192)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBody(Lower.kt:171)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitBlockBody(IrElementVisitor.kt:163)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBlockBody(Lower.kt:171)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitBlockBody(Lower.kt:171)
	at org.jetbrains.kotlin.ir.expressions.IrBlockBody.accept(IrBlockBody.kt:25)
	at org.jetbrains.kotlin.ir.declarations.IrFunction.acceptChildren(IrFunction.kt:54)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:180)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitDeclaration(Lower.kt:171)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitFunction(IrElementVisitor.kt:112)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:171)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitFunction(Lower.kt:171)
	at org.jetbrains.kotlin.ir.visitors.IrElementVisitor$DefaultImpls.visitConstructor(IrElementVisitor.kt:116)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitConstructor(Lower.kt:171)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitConstructor(Lower.kt:171)
	at org.jetbrains.kotlin.ir.declarations.IrConstructor.accept(IrConstructor.kt:30)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitClass(Lower.kt:186)
	at org.jetbrains.kotlin.backend.common.BodyLoweringVisitor.visitClass(Lower.kt:171)
	at org.jetbrains.kotlin.ir.declarations.IrClass.accept(IrClass.kt:73)
	at org.jetbrains.kotlin.backend.common.LowerKt.runOnFilePostfix(Lower.kt:150)
	at org.jetbrains.kotlin.backend.common.lower.InitializersLowering.lower(InitializersLowering.kt:28)
	at org.jetbrains.kotlin.backend.common.LowerKt.lower(Lower.kt:76)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeJsModulePhase$1.invoke(JsLoweringPhases.kt:48)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeJsModulePhase$1.invoke(JsLoweringPhases.kt:47)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:71)
	at org.jetbrains.kotlin.ir.backend.js.JsLoweringPhasesKt$makeCustomJsModulePhase$1.invoke(JsLoweringPhases.kt:63)
	at org.jetbrains.kotlin.backend.common.phaser.NamedCompilerPhase.phaseBody(CompilerPhase.kt:147)
	at org.jetbrains.kotlin.backend.common.phaser.AbstractNamedCompilerPhase.invoke(CompilerPhase.kt:94)
	at org.jetbrains.kotlin.ir.backend.js.CompilerWithICKt.lowerPreservingTags(compilerWithIC.kt:85)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compileIr(compiler.kt:135)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile(compiler.kt:56)
	at org.jetbrains.kotlin.ir.backend.js.CompilerKt.compile$default(compiler.kt:39)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.lowerIr(K2JsIrCompiler.kt:103)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.makeJsCodeGenerator(K2JsIrCompiler.kt:125)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler$Ir2JsTransformer.compileAndTransformIrNew(K2JsIrCompiler.kt:133)
	at org.jetbrains.kotlin.cli.js.K2JsIrCompiler.doExecute(K2JsIrCompiler.kt:391)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:181)
	at org.jetbrains.kotlin.cli.js.K2JSCompiler.doExecute(K2JSCompiler.java:72)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:104)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:48)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:101)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1523)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:360)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:712)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:587)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:828)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:705)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:704)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.IllegalStateException: Parent of this declaration is not a class: CONSTRUCTOR MISSING_DECLARATION visibility:public <> () returnType:kotlin.Nothing
	... 111 more
```

**Comment by robertfmurdock** [comment]
Seeing this now, will take a look. Hope all is well!

**Comment by robertfmurdock** [comment]
5.3.0 involved some changes to kotlin-wrappers that moved some on minreact's dependencies, so it couldn't hurt to ensure kotlin-wrappers is up to date. Coincidentally, I found a bug in kotlin-wrappers last week that they fixed a few days ago - I don't think its related, but they *are* the upstream dependency. https://github.com/JetBrains/kotlin-wrappers/issues/2193

The constructor-missing-declaration does suggest a dependency mismatch somewhere though... looks like 5.3.0 was matched to kotlin-wrappers 681. The newest versions of jsmints match current kotlin-wrappers of course.

Hard for me to help much more as is though, as I haven't seen this happen anywhere myself. If it keeps popping up, a minimal-viable reproduction would help me assist a lot.

**Comment by gad2103** [comment]
Hey thanks for the reply. This makes more sense. We pinned wrappers because the library was changing so often and we put the old UI into maintenance mode while we build a new one in TS/React. I guess we'll need to pin this library to the last working version too. hope all is well with you!
